[package]
name = "server_rust"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "utils",
    "http",
]

[dependencies]
utils = { path = "./utils"}
http = { path = "./http"}


reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }